@RestaurantsAPI_HostAddress = https://localhost:7248

GET {{RestaurantsAPI_HostAddress}}/api/restaurants

###

GET {{RestaurantsAPI_HostAddress}}/api/restaurants/5

###

POST {{RestaurantsAPI_HostAddress}}/api/restaurants
Content-Type: application/json
{
  "Name": "Test Restaurant 2",
  "Description": "A culinary experience like no other.",
  "Category": "Mexican",
  "HasDelivery": true,
  "ContactEmail": "test@info.com",
  "ContactNumber": "555-123-4567",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "51-535"
}
